
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/joinq
    username: godwin
    password: aquinas137
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update

server:
  error:
    include-stacktrace: never
